# Nombre del flujo de trabajo
name: Deploy and Test

# Define en qué eventos se ejecutará este flujo de trabajo
on:
  # 1. Se ejecuta para el Despliegue Final (en la rama principal)
  push:
    branches:
      - main  # Despliega automáticamente en Heroku cuando se fusiona a 'main'

  # 2. Se ejecuta para la Integración Continua (cuando se abre o actualiza un PR)
  pull_request:
    branches:
      - main  # Ejecuta las pruebas antes de permitir la fusión

# Los 'jobs' son los pasos que se ejecutan en el flujo de trabajo
jobs:
  build:
    # Sistema operativo donde se ejecutará el 'job'
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Obtiene el código de tu repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # === Zona de INTEGRACIÓN CONTINUA (CI) ===
      # Esta sección se ejecuta SIEMPRE (en push y pull_request)
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x' # Puedes cambiar la versión de Node.js aquí
          cache: 'npm' # Habilita la caché para instalaciones rápidas
          
      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Run Tests (Opcional, pero recomendado)
        # Si tienes scripts de prueba en package.json (ej: "test": "jest"), se ejecutan aquí.
        # Si esta etapa falla, el workflow se detiene y NO despliega.
        run: npm test # Si no tienes pruebas, puedes comentar o borrar esta línea.

      # === Zona de DESPLIEGUE CONTINUO (CD) ===
      # Paso 2: Despliega en Heroku
      # La condición 'if: github.event_name == 'push'' asegura que SÓLO se despliega
      # cuando el código ya ha pasado las pruebas y se ha hecho 'push' a la rama principal.
      - name: Deploy to Heroku
        if: github.event_name == 'push'
        uses: akhileshns/heroku-deploy@v3.12.12 # Utiliza la acción de despliegue de Heroku
        with:
          # Estas variables de entorno se definen en los "secrets" de GitHub
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "evaluaciondevops"  # Reemplaza con el nombre de tu app en Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }} # Ahora usa un "secret" para tu email
          
